[tool.poetry]
name = "MLOPS_Template"
version = "0.1.0"
description = ""
authors = ["wolffy-au <wolffborg1@gmail.com>"]
license = "GPL-3"
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.9,<3.13"
numpy = "^1.25.0"
scipy = "^1.11.1"
matplotlib = "^3.8.0"
pandas = "^2.0.3"
scikit-learn = "^1.3.2"
joblib = "^1.3.2"
pytest = "^7"
xgboost = "^1.7.6"

[tool.poetry.group.dev.dependencies]
ipykernel = "^6.27.1"
pyright = "^1.1"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.pyright]
# Optional: Specify the Python version for Pyright to use
pythonVersion = "3.11"

# Optional: Specify additional search paths for modules
# This is useful if your project has a non-standard structure
# For example, if your source code is in the 'src' directory:
searchPaths = ["src"]
