[tool.poetry]
name = "MLOPS_Template"
version = "0.1.0"
description = ""
authors = ["wolffy-au <wolffborg1@gmail.com>"]
license = "GPL-3"
readme = "README.md"

[tool.poetry.dependencies]
#python = ">=3.6.1"
#numpy = ">=1.19.5"
python = ">=3.9"
numpy = ">=1.23.5"
scipy = ">=1.5.4"
matplotlib = ">=3.3.4"
pandas = ">=1.1.5"
scikit-learn = ">=0.24.2"
joblib = ">=1.1.1"

#ninja = "1.5.3"
#contourpy = "1.0.7"
#certifi = "2020.06.20"
#setuptools = "68.2.2"
#setuptools_scm = "7.1.0"

[tool.poetry.group.dev.dependencies]
pytest = ">=7.0.1"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
