[tool.poetry]
name = "MLOPS_Template"
version = "0.1.0"
description = ""
authors = ["wolffy-au <wolffborg1@gmail.com>"]
license = "GPL-3"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9"
ninja = "1.5.3"
numpy = "1.23.5"
scipy = "1.9.3"
matplotlib = "3.6.3"
pandas = "1.5.3"
scikit-learn = "1.3.2"
joblib = "1.1.1"

[tool.poetry.group.dev.dependencies]
pytest = "^7.4.3"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
