pipeline {
    agent any

    environment {
        PYTHON_HOME = tool 'Python3'
        GIT_CREDENTIALS = credentials('1feb3df2-c165-4ef1-b4f4-2b195de9e731')
    }

    stages {
        stage('Checkout') {
            steps {
                script {
                    // Checkout source code from Gitea repository
                    checkout([
                        $class: 'GitSCM',
                        branches: [[name: 'MLTutorial']],  // Update to your actual branch name
                        userRemoteConfigs: [[
                            url: 'http://10.61.1.15:3000/wolffy-au/MLOPS_Template.git',
                            credentialsId: GIT_CREDENTIALS
                        ]]
                    ])
                }
            }
        }

        stage('Build') {
            steps {
                script {
                    // sh "pkg upgrade python39 py39-pip py39-numpy py39-scipy py39-matplotlib py39-pandas py39-scikit-learn py39-joblib"
                    sh "${PYTHON_HOME}pip3 install -r requirements.txt"
                }
            }
        }

        stage('Test') {
            steps {
                script {
                    sh "${PYTHON_HOME}python -m pytest"
                }
            }
        }

        stage('Deploy') {
            steps {
                echo "Add deployment steps here"
                // Add deployment steps as needed
                sh "${PYTHON_HOME}python src/5_inference.py"
            }
        }
    }
}
